2021-07-01T11:59:52.317946+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,317] telethon.network.mtprotosender: Connection to 149.154.175.51:443/TcpFull complete!
2021-07-01T11:59:52.436125+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,435] telethon.network.mtprotosender: Disconnecting from 149.154.175.51:443/TcpFull...
2021-07-01T11:59:52.436646+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,436] telethon.network.mtprotosender: Disconnection from 149.154.175.51:443/TcpFull complete!
2021-07-01T11:59:52.437260+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,437] telethon.network.mtprotosender: Connecting to 149.154.175.51:443/TcpFull...
2021-07-01T11:59:52.463918+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,463] telethon.network.mtprotosender: Connection to 149.154.175.51:443/TcpFull complete!
2021-07-01T11:59:52.761182+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,760] telethon.network.mtprotosender: Disconnecting from 149.154.175.51:443/TcpFull...
2021-07-01T11:59:52.762039+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,761] telethon.network.mtprotosender: Disconnection from 149.154.175.51:443/TcpFull complete!
2021-07-01T11:59:52.763487+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:29:52,763] telethon.client.uploads: Uploading file of 48325 bytes in 1 chunks of 131072
2021-07-01T12:00:09.399408+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,399] telethon.network.mtprotosender: Connecting to 149.154.175.51:443/TcpFull...
2021-07-01T12:00:09.426219+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,425] telethon.network.mtprotosender: Connection to 149.154.175.51:443/TcpFull complete!
2021-07-01T12:00:09.621705+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,621] telethon.network.mtprotosender: Disconnecting from 149.154.175.51:443/TcpFull...
2021-07-01T12:00:09.623227+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,623] telethon.network.mtprotosender: Disconnection from 149.154.175.51:443/TcpFull complete!
2021-07-01T12:00:09.623926+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,623] telethon.network.mtprotosender: Connecting to 149.154.175.51:443/TcpFull...
2021-07-01T12:00:09.651209+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,650] telethon.network.mtprotosender: Connection to 149.154.175.51:443/TcpFull complete!
2021-07-01T12:00:09.857260+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,856] telethon.network.mtprotosender: Disconnecting from 149.154.175.51:443/TcpFull...
2021-07-01T12:00:09.857889+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,857] telethon.network.mtprotosender: Disconnection from 149.154.175.51:443/TcpFull complete!
2021-07-01T12:00:09.858812+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:30:09,858] telethon.client.uploads: Uploading file of 48325 bytes in 1 chunks of 131072
2021-07-01T12:19:31.821842+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:49:31,821] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-01T12:19:55.572447+00:00 app[ultroid.1]: [ INFO/2021-07-01 17:49:55,572] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-01T12:43:35.714966+00:00 app[ultroid.1]: [ INFO/2021-07-01 18:13:35,714] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-01T12:44:41.577595+00:00 app[ultroid.1]: [ERROR/2021-07-01 18:14:41,573] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T12:44:41.577634+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T12:44:41.577635+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/inlinebuilder.py", line 300, in document
2021-07-01T12:44:41.577635+00:00 app[ultroid.1]:     fh = utils.get_input_document(file)
2021-07-01T12:44:41.577635+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/utils.py", line 344, in get_input_document
2021-07-01T12:44:41.577636+00:00 app[ultroid.1]:     return get_input_document(document.media)
2021-07-01T12:44:41.577636+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/utils.py", line 346, in get_input_document
2021-07-01T12:44:41.577637+00:00 app[ultroid.1]:     _raise_cast_fail(document, 'InputDocument')
2021-07-01T12:44:41.577637+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
2021-07-01T12:44:41.577637+00:00 app[ultroid.1]:     raise TypeError('Cannot cast {} to any kind of {}.'.format(
2021-07-01T12:44:41.577638+00:00 app[ultroid.1]: TypeError: Cannot cast MessageMediaPhoto to any kind of InputDocument.
2021-07-01T12:44:41.577639+00:00 app[ultroid.1]: 
2021-07-01T12:44:41.577639+00:00 app[ultroid.1]: During handling of the above exception, another exception occurred:
2021-07-01T12:44:41.577639+00:00 app[ultroid.1]: 
2021-07-01T12:44:41.577639+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T12:44:41.577640+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T12:44:41.577640+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T12:44:41.577641+00:00 app[ultroid.1]:   File "/root/TeamUltroid/addons/btnsss.py", line 113, in query_ibutton
2021-07-01T12:44:41.577641+00:00 app[ultroid.1]:     await event.answer([result] if result else None)
2021-07-01T12:44:41.577641+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/events/inlinequery.py", line 221, in answer
2021-07-01T12:44:41.577641+00:00 app[ultroid.1]:     results = [x.result() for x in futures]
2021-07-01T12:44:41.577641+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/events/inlinequery.py", line 221, in <listcomp>
2021-07-01T12:44:41.577642+00:00 app[ultroid.1]:     results = [x.result() for x in futures]
2021-07-01T12:44:41.577642+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/inlinebuilder.py", line 314, in document
2021-07-01T12:44:41.577642+00:00 app[ultroid.1]:     r = await self._client(functions.messages.UploadMediaRequest(
2021-07-01T12:44:41.577642+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
2021-07-01T12:44:41.577643+00:00 app[ultroid.1]:     result = await future
2021-07-01T12:44:41.577643+00:00 app[ultroid.1]: telethon.errors.rpcerrorlist.MediaInvalidError: Media invalid (caused by UploadMediaRequest)
2021-07-01T12:44:50.299964+00:00 app[ultroid.1]: [WARNING/2021-07-01 18:14:50,299] py.warnings: /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'virginia.sessions.logs.heroku.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-07-01T12:44:50.299981+00:00 app[ultroid.1]:   warnings.warn(
2021-07-01T12:44:50.299983+00:00 app[ultroid.1]: 
2021-07-01T12:44:50.373964+00:00 app[ultroid.1]: [ INFO/2021-07-01 18:14:50,373] telethon.client.uploads: Uploading file of 12757 bytes in 1 chunks of 131072
2021-07-01T13:44:25.642852+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:14:25,642] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:44:25.642864+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:44:25.642865+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:44:25.642866+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:44:25.642866+00:00 app[ultroid.1]:   File "<string>", line 11, in query_ibutton
2021-07-01T13:44:25.642867+00:00 app[ultroid.1]: NameError: name 'query' is not defined
2021-07-01T13:44:35.891763+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:14:35,891] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:44:35.891773+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:44:35.891800+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:44:35.891801+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:44:35.891802+00:00 app[ultroid.1]:   File "<string>", line 11, in query_ibutton
2021-07-01T13:44:35.891802+00:00 app[ultroid.1]: NameError: name 'query' is not defined
2021-07-01T13:44:37.307727+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:14:37,307] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:44:37.307742+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:44:37.307760+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:44:37.307761+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:44:37.307761+00:00 app[ultroid.1]:   File "<string>", line 11, in query_ibutton
2021-07-01T13:44:37.307761+00:00 app[ultroid.1]: NameError: name 'query' is not defined
2021-07-01T13:44:38.778855+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:14:38,778] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:44:38.778871+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:44:38.778872+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:44:38.778872+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:44:38.778873+00:00 app[ultroid.1]:   File "<string>", line 11, in query_ibutton
2021-07-01T13:44:38.778873+00:00 app[ultroid.1]: NameError: name 'query' is not defined
2021-07-01T13:44:42.242190+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:14:42,241] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:44:42.242202+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:44:42.242203+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:44:42.242204+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:44:42.242205+00:00 app[ultroid.1]:   File "<string>", line 11, in query_ibutton
2021-07-01T13:44:42.242205+00:00 app[ultroid.1]: NameError: name 'query' is not defined
2021-07-01T13:44:45.402953+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:14:45,402] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:44:45.402962+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:44:45.402963+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:44:45.402964+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:44:45.402964+00:00 app[ultroid.1]:   File "<string>", line 11, in query_ibutton
2021-07-01T13:44:45.402965+00:00 app[ultroid.1]: NameError: name 'query' is not defined
2021-07-01T13:46:21.864111+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:16:21,863] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:46:21.864129+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:46:21.864130+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:46:21.864132+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:46:21.864132+00:00 app[ultroid.1]:   File "<string>", line 11, in query_ibutton
2021-07-01T13:46:21.864132+00:00 app[ultroid.1]: NameError: name 'query' is not defined
2021-07-01T13:54:18.981989+00:00 app[ultroid.1]: [ERROR/2021-07-01 19:24:18,981] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-01T13:54:18.982006+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-01T13:54:18.982018+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-01T13:54:18.982019+00:00 app[ultroid.1]:     await callback(event)
2021-07-01T13:54:18.982019+00:00 app[ultroid.1]:   File "<string>", line 9, in query_ibutton
2021-07-01T13:54:18.982021+00:00 app[ultroid.1]: TypeError: photo() got an unexpected keyword argument 'description'
